### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by nguyen1004** [SkyTechBytes/PlayerStatueBuilder#11]
when i try to build my skin , they said cant load skin from api

**Comment by imbloob** [comment]
I have the same issue on my server.

**Comment by SkyTechBytes** [comment]
Hello, thanks for the report. The issue seems to be that crafatar (which is how the plugin obtains player skins) was down for a few days. Since the crafatar API seems to be up now, the plugin should work again. I'm currently working on an update that will try to obtain the skin from multiple websites before failing so this is less likely to occur in the future.
