### ISSUE TITLE
Console build

### ISSUE THREAD

**Issue by TomLewis** [SkyTechBytes/PlayerStatueBuilder#16]
Can we please be able to build a statue via console so we can automate a status placement, I want to use it for recent contributors to the server to automate placement of a statue.

**Comment by SkyTechBytes** [comment]
The plugin currently has an API that you can use to place a statue https://github.com/SkyTechBytes/PlayerStatueBuilder/blob/master/src/com/skytechbytes/api/PlayerStatueBuilderAPI.java . Calling this function will allow you to place a statue at a specific Location (which includes coordinates and world information). I can look into creating a statue without a player running the command but the issue is determining which world the statue should be created in.

**Comment by TomLewis** [comment]
Ahh sadly I dont know Java, but if you can add parameters to the command to build to input the world/cordinates, then make where it pastes maybe the middle point of the statue? then we can figure it out from there.

Could be used for all sorts if you can automate statue building from other plugins.

Could use it on mini games for a winner of a tournament! that would be cool!

**Comment by SkyTechBytes** [comment]
Hey! I've been looking into making this a reality and there's now a release with this feature available for testing: https://github.com/SkyTechBytes/PlayerStatueBuilder/releases/tag/1.16 
Feel free to try it out!

**Comment by TomLewis** [comment]
This is fantastic news! Ive seen you added a release to spigot, I just tried it on my creative to test it, but sadly support is dropped for 1.18.2 so cant use it :(

Not had the chance to do testing on all my plugins for my network yet for 1.20+ so im stuck on 1.18 for a while still.
